### ISSUE TITLE
Connection timed out error after script has been running for a while

### ISSUE THREAD

**Issue by hc-nolan** [chunned/espcap-opcua#6]
When the script is left sitting for a longer amount of time (~1 hour) it seems to time out for some reason:
```bash
Traceback (most recent call last):
  File "/home/hayden/asherah-master/EShark/main.py", line 1080, in <module>
    main(arguments)
  File "/home/hayden/asherah-master/EShark/main.py", line 1075, in main
    capture(es, capture_mode, interface, pcapfile, bpf, packet_count)
  File "/home/hayden/asherah-master/EShark/main.py", line 341, in capture
    helpers.bulk(client=es, actions=index_packets(cap=packets))
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 339, in _process_bulk_chunk
    resp = client.bulk(*args, operations=bulk_actions, **kwargs)  # type: ignore[arg-type]
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 446, in wrapped
    return api(*args, **kwargs)
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 717, in bulk
    return self.perform_request(  # type: ignore[return-value]
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 271, in perform_request
    response = self._perform_request(
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 316, in _perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elastic_transport/_transport.py", line 342, in perform_request
    resp = node.perform_request(
  File "/home/hayden/asherah-master/EShark/venv/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionTimeout: Connection timed out
```

EShark logs:
```bash
2024-08-22 18:14:07,462 PUT http://localhost:9200/_bulk [status:N/A duration:10.564s]
2024-08-22 18:14:07,462 Node <Urllib3HttpNode(http://localhost:9200)> has failed for 1 times in a row, putting on 1 second timeout
```

ElasticSearch logs:
```bash
{"@timestamp":"2024-08-22T20:31:03.936Z", "log.level": "WARN", "message":"Too many buckets (max [65536], count [66285])", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][search][T#1]","log.logger":"org.elasticsearch.search.aggregations.MultiBucketConsumerService.MultiBucketConsumer","trace.id":"ee9ba3f5fcebcc890c48e6100b732c07","elasticsearch.cluster.uuid":"F4tUJgcsSQWCTlTxVNGyCw","elasticsearch.node.id":"GP8Ocov5QheY-Z2WUUs3Iw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-08-22T21:27:45.782Z", "log.level": "WARN", "message":"timer thread slept for [5.9s/5947ms] on absolute clock which is above the warn threshold of [5000ms]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][[timer]]","log.logger":"org.elasticsearch.threadpool.ThreadPool","elasticsearch.cluster.uuid":"F4tUJgcsSQWCTlTxVNGyCw","elasticsearch.node.id":"GP8Ocov5QheY-Z2WUUs3Iw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-08-22T21:27:45.782Z", "log.level": "WARN", "message":"timer thread slept for [5.9s/5946642905ns] on relative clock which is above the warn threshold of [5000ms]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][[timer]]","log.logger":"org.elasticsearch.threadpool.ThreadPool","elasticsearch.cluster.uuid":"F4tUJgcsSQWCTlTxVNGyCw","elasticsearch.node.id":"GP8Ocov5QheY-Z2WUUs3Iw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-08-22T21:28:10.838Z", "log.level": "WARN", "message":"timer thread slept for [19s/19088ms] on absolute clock which is above the warn threshold of [5000ms]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][[timer]]","log.logger":"org.elasticsearch.threadpool.ThreadPool","elasticsearch.cluster.uuid":"F4tUJgcsSQWCTlTxVNGyCw","elasticsearch.node.id":"GP8Ocov5QheY-Z2WUUs3Iw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-08-22T21:28:10.839Z", "log.level": "WARN", "message":"timer thread slept for [19s/19087735443ns] on relative clock which is above the warn threshold of [5000ms]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][[timer]]","log.logger":"org.elasticsearch.threadpool.ThreadPool","elasticsearch.cluster.uuid":"F4tUJgcsSQWCTlTxVNGyCw","elasticsearch.node.id":"GP8Ocov5QheY-Z2WUUs3Iw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-08-22T21:28:12.182Z", "log.level": "WARN", "message":"Received response for a request that has timed out, sent [32.3s/32343ms] ago, timed out [1.3s/1340ms] ago, action [indices:monitor/stats[n]], node [{elasticsearch}{GP8Ocov5QheY-Z2WUUs3Iw}{MPQmabyfRKu92mOy8cqFjg}{elasticsearch}{172.18.0.2}{172.18.0.2:9300}{cdfhilmrstw}{8.15.0}{7000099-8512000}{ml.machine_memory=20972634112, transform.config_version=10.0.0, xpack.installed=true, ml.config_version=12.0.0, ml.max_jvm_size=536870912, ml.allocated_processors_double=6.0, ml.allocated_processors=6}], id [538306]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][management][T#4]","log.logger":"org.elasticsearch.transport.TransportService","elasticsearch.cluster.uuid":"F4tUJgcsSQWCTlTxVNGyCw","elasticsearch.node.id":"GP8Ocov5QheY-Z2WUUs3Iw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-08-22T21:28:13.602Z", "log.level": "WARN", "message":"failed to retrieve shard stats from node [GP8Ocov5QheY-Z2WUUs3Iw]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][management][T#2]","log.logger":"org.elasticsearch.cluster.InternalClusterInfoService","elasticsearch.cluster.uuid":"F4tUJgcsSQWCTlTxVNGyCw","elasticsearch.node.id":"GP8Ocov5QheY-Z2WUUs3Iw","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster","error.type":"org.elasticsearch.transport.ReceiveTimeoutTransportException","error.message":"[elasticsearch][172.18.0.2:9300][indices:monitor/stats[n]] request_id [538306] timed out after [31003ms]","error.stack_trace":"org.elasticsearch.transport.ReceiveTimeoutTransportException: [elasticsearch][172.18.0.2:9300][indices:monitor/stats[n]] request_id [538306] timed out after [31003ms]\n"}
```

**Comment by hc-nolan** [comment]
There does appear to be an increase in the average request duration, but nothing that should be causing timeouts:

```bash
cat eshark-20240822-173756.log | grep duration

2024-08-22 18:13:54,388 PUT http://localhost:9200/_bulk [status:200 duration:0.008s]
2024-08-22 18:13:54,395 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:54,403 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:54,410 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:54,417 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:54,425 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:54,555 PUT http://localhost:9200/_bulk [status:200 duration:0.046s]
2024-08-22 18:13:54,566 PUT http://localhost:9200/_bulk [status:200 duration:0.009s]
2024-08-22 18:13:54,605 PUT http://localhost:9200/_bulk [status:200 duration:0.020s]
2024-08-22 18:13:54,612 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:54,750 PUT http://localhost:9200/_bulk [status:200 duration:0.050s]
2024-08-22 18:13:54,757 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:54,791 PUT http://localhost:9200/_bulk [status:200 duration:0.017s]
2024-08-22 18:13:54,799 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:54,914 PUT http://localhost:9200/_bulk [status:200 duration:0.042s]
2024-08-22 18:13:54,922 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:54,955 PUT http://localhost:9200/_bulk [status:200 duration:0.016s]
2024-08-22 18:13:54,962 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:55,083 PUT http://localhost:9200/_bulk [status:200 duration:0.040s]
2024-08-22 18:13:55,098 PUT http://localhost:9200/_bulk [status:200 duration:0.011s]
2024-08-22 18:13:55,143 PUT http://localhost:9200/_bulk [status:200 duration:0.017s]
2024-08-22 18:13:55,152 PUT http://localhost:9200/_bulk [status:200 duration:0.007s]
2024-08-22 18:13:55,281 PUT http://localhost:9200/_bulk [status:200 duration:0.056s]
2024-08-22 18:13:55,288 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:55,322 PUT http://localhost:9200/_bulk [status:200 duration:0.017s]
2024-08-22 18:13:55,330 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:55,447 PUT http://localhost:9200/_bulk [status:200 duration:0.040s]
2024-08-22 18:13:55,454 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:55,487 PUT http://localhost:9200/_bulk [status:200 duration:0.015s]
2024-08-22 18:13:55,493 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:55,509 PUT http://localhost:9200/_bulk [status:200 duration:0.011s]
2024-08-22 18:13:55,516 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:55,532 PUT http://localhost:9200/_bulk [status:200 duration:0.011s]
2024-08-22 18:13:55,539 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:13:55,663 PUT http://localhost:9200/_bulk [status:200 duration:0.047s]
2024-08-22 18:13:55,671 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:55,722 PUT http://localhost:9200/_bulk [status:200 duration:0.029s]
2024-08-22 18:13:55,731 PUT http://localhost:9200/_bulk [status:200 duration:0.007s]
2024-08-22 18:13:55,877 PUT http://localhost:9200/_bulk [status:200 duration:0.044s]
2024-08-22 18:13:55,886 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:55,931 PUT http://localhost:9200/_bulk [status:200 duration:0.020s]
2024-08-22 18:13:55,939 PUT http://localhost:9200/_bulk [status:200 duration:0.006s]
2024-08-22 18:13:56,070 PUT http://localhost:9200/_bulk [status:200 duration:0.048s]
2024-08-22 18:13:56,083 PUT http://localhost:9200/_bulk [status:200 duration:0.010s]
2024-08-22 18:13:56,409 PUT http://localhost:9200/_bulk [status:200 duration:0.305s]
2024-08-22 18:13:56,439 PUT http://localhost:9200/_bulk [status:200 duration:0.027s]
2024-08-22 18:13:56,585 PUT http://localhost:9200/_bulk [status:200 duration:0.062s]
2024-08-22 18:13:56,628 PUT http://localhost:9200/_bulk [status:200 duration:0.040s]
2024-08-22 18:13:56,674 PUT http://localhost:9200/_bulk [status:200 duration:0.026s]
2024-08-22 18:13:56,688 PUT http://localhost:9200/_bulk [status:200 duration:0.011s]
2024-08-22 18:13:56,871 PUT http://localhost:9200/_bulk [status:200 duration:0.108s]
2024-08-22 18:13:56,879 PUT http://localhost:9200/_bulk [status:200 duration:0.005s]
2024-08-22 18:14:07,462 PUT http://localhost:9200/_bulk [status:N/A duration:10.564s]
```

**Comment by hc-nolan** [comment]
https://github.com/chunned/EShark/commit/dbcbe23b26a452ad1392a18cf10fe155915b1016

Added a timeout handler so the script no longer crashes.
